// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"reflect"
	"github.com/petergtz/pegomock"
	boshdirector "github.com/pivotal-cf/on-demand-service-broker/boshdirector"
)

func AnyBoshdirectorBoshTasks() boshdirector.BoshTasks {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(boshdirector.BoshTasks))(nil)).Elem()))
	var nullValue boshdirector.BoshTasks
	return nullValue
}

func EqBoshdirectorBoshTasks(value boshdirector.BoshTasks) boshdirector.BoshTasks {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue boshdirector.BoshTasks
	return nullValue
}
