// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"reflect"
	"github.com/petergtz/pegomock"
	boshdirector "github.com/pivotal-cf/on-demand-service-broker/boshdirector"
)

func AnyBoshdirectorInfo() boshdirector.Info {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(boshdirector.Info))(nil)).Elem()))
	var nullValue boshdirector.Info
	return nullValue
}

func EqBoshdirectorInfo(value boshdirector.Info) boshdirector.Info {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue boshdirector.Info
	return nullValue
}
