// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"reflect"
	"github.com/petergtz/pegomock"
	domain "github.com/pivotal-cf/brokerapi/domain"
)

func AnyDomainServiceSchemas() domain.ServiceSchemas {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(domain.ServiceSchemas))(nil)).Elem()))
	var nullValue domain.ServiceSchemas
	return nullValue
}

func EqDomainServiceSchemas(value domain.ServiceSchemas) domain.ServiceSchemas {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue domain.ServiceSchemas
	return nullValue
}
