// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"reflect"
	"github.com/petergtz/pegomock"
	boshdirector "github.com/pivotal-cf/on-demand-service-broker/boshdirector"
)

func AnyPtrToBoshdirectorAsyncTaskReporter() *boshdirector.AsyncTaskReporter {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(*boshdirector.AsyncTaskReporter))(nil)).Elem()))
	var nullValue *boshdirector.AsyncTaskReporter
	return nullValue
}

func EqPtrToBoshdirectorAsyncTaskReporter(value *boshdirector.AsyncTaskReporter) *boshdirector.AsyncTaskReporter {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue *boshdirector.AsyncTaskReporter
	return nullValue
}
