// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"reflect"
	"github.com/petergtz/pegomock"
	serviceadapter "github.com/pivotal-cf/on-demand-services-sdk/serviceadapter"
)

func AnyServiceadapterBinding() serviceadapter.Binding {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(serviceadapter.Binding))(nil)).Elem()))
	var nullValue serviceadapter.Binding
	return nullValue
}

func EqServiceadapterBinding(value serviceadapter.Binding) serviceadapter.Binding {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue serviceadapter.Binding
	return nullValue
}
