// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"reflect"
	"github.com/petergtz/pegomock"
	config "github.com/pivotal-cf/on-demand-service-broker/config"
)

func AnySliceOfConfigBindingDNS() []config.BindingDNS {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*([]config.BindingDNS))(nil)).Elem()))
	var nullValue []config.BindingDNS
	return nullValue
}

func EqSliceOfConfigBindingDNS(value []config.BindingDNS) []config.BindingDNS {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue []config.BindingDNS
	return nullValue
}
