// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"reflect"
	"github.com/petergtz/pegomock"
	boshdirector "github.com/pivotal-cf/on-demand-service-broker/boshdirector"
)

func AnySliceOfBoshdirectorVariable() []boshdirector.Variable {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*([]boshdirector.Variable))(nil)).Elem()))
	var nullValue []boshdirector.Variable
	return nullValue
}

func EqSliceOfBoshdirectorVariable(value []boshdirector.Variable) []boshdirector.Variable {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue []boshdirector.Variable
	return nullValue
}
