// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"reflect"
	"github.com/petergtz/pegomock"
	boshdirector "github.com/pivotal-cf/on-demand-service-broker/boshdirector"
)

func AnySliceOfBoshdirectorBoshConfig() []boshdirector.BoshConfig {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*([]boshdirector.BoshConfig))(nil)).Elem()))
	var nullValue []boshdirector.BoshConfig
	return nullValue
}

func EqSliceOfBoshdirectorBoshConfig(value []boshdirector.BoshConfig) []boshdirector.BoshConfig {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue []boshdirector.BoshConfig
	return nullValue
}
