// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"reflect"
	"github.com/petergtz/pegomock"
	boshdirector "github.com/pivotal-cf/on-demand-service-broker/boshdirector"
)

func AnySliceOfBoshdirectorDeployment() []boshdirector.Deployment {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*([]boshdirector.Deployment))(nil)).Elem()))
	var nullValue []boshdirector.Deployment
	return nullValue
}

func EqSliceOfBoshdirectorDeployment(value []boshdirector.Deployment) []boshdirector.Deployment {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue []boshdirector.Deployment
	return nullValue
}
